name: Validation

on:
  schedule:
    - cron: '50 7 * * 1-6'   # À 9h50 
    - cron: '20 12 * * *'  # À 14h20 
    - cron: '50 16 * * *'    # À 18h50 
    - cron: '50 15 * * 6'    # À 17h50 


jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Send POST Requests for Multiple Emails and Check for Errors
        run: |
          EMAILS=("leo.rocheteau1@etu.univ-nantes.fr" "donatien.merlant@etu.univ-nantes.fr" "margaux.ouertal@etu.univ-nantes.fr" "sixtine.audousset@etu.univ-nantes.fr" "fanny.deckert@etu.univ-nantes.fr" "gabriel.vlaeminck@etu.univ-nantes.fr" "cleo.di-peri@etu.univ-nantes.fr" "paula.fabre@etu.univ-nantes.fr" "louis.boutin2@etu.univ-nantes.fr")
          VALIDATION_CODE="CEUZ"
          for EMAIL in "${EMAILS[@]}"
          do
            RESPONSE=$(curl -X POST "https://reservation.affluences.com/api/validateReservation" \
            -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" \
            -H "Accept: application/json, text/plain, */*" \
            -H "Accept-Language: fr" \
            -H "Content-Type: application/json" \
            -H "Sec-Fetch-Dest: empty" \
            -H "Sec-Fetch-Mode: cors" \
            -H "Sec-Fetch-Site: same-site" \
            -H "Sec-GPC: 1" \
            -d "{\"validationCode\":\"$VALIDATION_CODE\",\"email\":\"$EMAIL\"}")
            echo "Request sent for $EMAIL"
            if [[ "$RESPONSE" == *"wrong_validation_code"* ]]; then
              echo "::error ::Validation error detected for $EMAIL"
              echo "::set-output name=create_issue::true"
            fi
          done
        id: error_check
      
      - name: Create Issue on Error
        if: steps.error_check.outputs.create_issue == 'true'
        uses: imjohnbo/issue-bot@v3
        with:
          title: "Validation Error Detected"
          body: "A validation error was detected during the scheduled POST requests. Please check the validation codes."
          labels: error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
