name: Validation

on:
  schedule:
    - cron: '50 8 * * 1-6'   # À 9h50 UTC+1
    - cron: '20 13 * * 1-6'  # À 14h20 UTC+1
    - cron: '50 17 * * *'  # À 18h50 UTC+1

jobs:
  make_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Send POST Requests for Multiple Emails
      run: |
        EMAILS=("leo.rocheteau1@etu.univ-nantes.fr" "castille.de-lavenne-de-la-montoise@etu.univ-nantes.fr" "alban.rousseau@etu.univ-nantes.fr" "louise.beaugendre@etu.univ-nantes.fr" "fanny.deckert@etu.univ-nantes.fr")
        for EMAIL in "${EMAILS[@]}"
        do
          curl -X POST "https://reservation.affluences.com/api/validateReservation" \
          -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" \
          -H "Accept: application/json, text/plain, */*" \
          -H "Accept-Language: fr" \
          -H "Content-Type: application/json" \
          -H "Sec-Fetch-Dest: empty" \
          -H "Sec-Fetch-Mode: cors" \
          -H "Sec-Fetch-Site: same-site" \
          -H "Sec-GPC: 1" \
          -d "{\"validationCode\":\"VP9B\",\"email\":\"$EMAIL\"}"
          echo "Request sent for $EMAIL"
        done
